#!/bin/sh

# This script will set up git to ignore some files that are actually in the repository
# It must be run from the top folder of the repository

echo Setting some files so that their changes will be ignored
git update-index --assume-unchanged ./Projects/Kerkerkruip.inform/Settings.plist
git update-index --assume-unchanged ./Projects/Kerkerkruip.inform/uuid.txt
git update-index --assume-unchanged ./Projects/Kerkerkruip.inform/Index/Headings.xml
echo Done!