#!/bin/bash

set -e -o pipefail

# This script will attempt to build Kerkerkruip with Travis CI

#./i7/bin/i7 -p ./i7 -s blorb=1,zcode=g -c Kerkerkruip.inform #2>&1 | grep -Ev "ve also read|\+\+ |::#+"
./i7/libexec/ni --internal ./i7/share/inform7/Internal --noprogress --format=ulx --project Kerkerkruip.inform | grep -Ev "ve also read"
./i7/libexec/inform6 -E2wSDG Kerkerkruip.inform/Build/auto.inf -o Kerkerkruip.inform/Build/output.ulx
./i7/libexec/cBlorb -unix Kerkerkruip.inform/Release.blurb Kerkerkruip.inform/Build/output.gblorb

cp Kerkerkruip.inform/Build/output.gblorb Kerkerkruip.gblorb
cp Kerkerkruip.materials/Kerkerkruip.ini Kerkerkruip.ini

upload_zip()
{
	zip kerkerkruip-git Kerkerkruip.gblorb Kerkerkruip.ini
	sshpass -e sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - ${KUSER}@${KSERVER} <<- !
		cd downloads.kerkerkruip.org
		put kerkerkruip-git.zip
		bye
	!
}

if [[ $TRAVIS_BRANCH == "master" ]]; then
	upload_zip || true
fi
