#!/usr/bin/env node

// This script will run Kerkerkruip's unit tests

console.log( 'Running the Kerkerkruip test suite:' );

var fs = require( 'fs' );
var spawn = require( 'child_process' ).spawn;

// Create the noninteractivetests file, which will, not entirely unexpectedly, run the tests non-interactively
var fd = fs.openSync( 'noninteractivetests', 'w' );
fs.closeSync( fd );

// Use unbuffer to force line buffering (otherwise we'd get all the output in one go)
var vm = spawn( 'unbuffer', [ '/usr/local/share/inform7/Interpreters/dumb-git', 'Kerkerkruip.gblorb' ] );

var completed = 0, testresults = 1;

vm.stdout.on( 'data', function ( data )
{
	data = data.toString();
	
	// We strip out most of the test output, but still print some progress markers
	if ( data.indexOf( 'Now testing' ) >= 0 )
	{
		process.stdout.write( '.' );
	}
	
	if ( data.indexOf( 'Test results' ) >= 0 )
	{
		completed = 1;
		process.stdout.write( '\n\n' );
	}
	
	// We're finished!
	if ( data.indexOf( 'To view a full transcript of all tests' ) >= 0 )
	{
		fs.unlinkSync( 'noninteractivetests' );
		process.exit( testresults );
	}
	
	// Unless there are 0 total failures the script will exit with 1
	if ( /Total: (\d+) tests, 0 failures/.test( data ) )
	{
		testresults = 0;
	}
	
	data = data.replace( /^(?!Total).+0 failures$/gm, '' ).trim();
	
	if ( completed && data )
	{
		console.log( data );
	}
	
	if ( data.indexOf( 'Total:' ) == 0 )
	{
		process.stdout.write( '\n' );
	}
});
