#!/bin/sh

# This script will attempt to build Kerkerkruip with Travis CI

i7 -s blorb=1,zcode=g -c Kerkerkruip.inform

mv Kerkerkruip.inform/Build/output.gblorb Kerkerkruip.gblorb
mv Kerkerkruip.materials/Kerkerkruip.ini Kerkerkruip.ini
zip Kerkerkruip-git Kerkerkruip.gblorb Kerkerkruip.ini

sshpass -e sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - ${KUSER}@${KSERVER} << !
	cd downloads.kerkerkruip.org
	put Kerkerkruip-git.zip
	bye
!